name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 15 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Tokyo
#           retries: 3
#           retries_delay: 300

          plugin_isocalendar: yes
          
          plugin_achievements: yes
#           plugin_achievements_only: >-
#             polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
#             scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          config_order: base.header,isocalendar,achievements
