name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - id: variable
        run: |
          echo '::set-output name=MY_TIMEZONE::Asia/Tokyo'
          echo '::set-output name=MY_RETRIES::2'
          echo '::set-output name=MY_RETRIES_DELAY::30'

      - uses: lowlighter/metrics@latest
        name: base-header
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}

          filename: github-metrics-base-header.svg
          base: header

      - uses: lowlighter/metrics@latest
        name: base
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}

          filename: github-metrics-base.svg

      - uses: lowlighter/metrics@latest
        name: base-isocalendar
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-isocalendar.svg
          plugin_isocalendar: yes

      - uses: lowlighter/metrics@latest
        name: languages
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-languages.svg
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

      - uses: lowlighter/metrics@latest
        name: topics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-topics.svg
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - uses: lowlighter/metrics@latest
        name: stars
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-stars.svg
          plugin_stars: yes
          plugin_stars_limit: 3

      - uses: lowlighter/metrics@latest
        name: licenses
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-licenses.svg
#           repo: metrics
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_licenses_legal: no
          plugin_licenses_ratio: yes

      - uses: lowlighter/metrics@latest
        name: habits
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-habits.svg
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes

      - uses: lowlighter/metrics@latest
        name: contributors
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-contributors.svg
          repo: metrics
          plugin_contributors: yes
          plugin_contributors_contributions: yes

      - uses: lowlighter/metrics@latest
        name: followup
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-followup.svg
          plugin_followup: yes
          plugin_followup_indepth: yes

      - uses: lowlighter/metrics@latest
        name: reactions
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-reactions.svg
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

      - uses: lowlighter/metrics@latest
        name: people
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-people.svg
          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, sponsors

      - uses: lowlighter/metrics@latest
        name: stargazers
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-stargazers.svg
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist

      - uses: lowlighter/metrics@latest
        name: code
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-code.svg
          plugin_code: yes
          plugin_code_load: 400

      - uses: lowlighter/metrics@latest
        name: activity
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-activity.svg
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0

      - uses: lowlighter/metrics@latest
        name: achievements
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""

          filename: github-metrics-achievements.svg
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

      - uses: lowlighter/metrics@latest
        name: notable
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-notable.svg
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

      - uses: lowlighter/metrics@latest
        name: discussions
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-discussions.svg
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8

      - uses: lowlighter/metrics@latest
        name: support
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-support.svg
          plugin_support: yes

      - uses: lowlighter/metrics@latest
        name: lines
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-lines.svg
          plugin_lines: yes

      - uses: lowlighter/metrics@latest
        name: traffic
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-traffic.svg
          plugin_traffic: yes

      - uses: lowlighter/metrics@latest
        name: repositories
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-repositories.svg
          plugin_repositories: yes

      - uses: lowlighter/metrics@latest
        name: gists
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-gists.svg
          plugin_gists: yes

      - uses: lowlighter/metrics@latest
        name: introduction
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-introduction.svg
          plugin_introduction: yes

      - uses: lowlighter/metrics@latest
        name: sponsors
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-sponsors.svg
          plugin_sponsors: yes

      - uses: lowlighter/metrics@latest
        name: starlists
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-starlists.svg
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome

      - uses: lowlighter/metrics@latest
        name: skyline
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-skyline.svg
          plugin_skyline: yes

      - uses: lowlighter/metrics@latest
        name: pagespeed
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: ${{steps.variable.outputs.MY_TIMEZONE}}
          retries: ${{steps.variable.outputs.MY_RETRIES}}
          retries_delay: ${{steps.variable.outputs.MY_RETRIES_DELAY}}
          base: ""
        
          filename: github-metrics-pagespeed.svg
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: https://github.com/nisioka/nisioka
